#!/bin/bash

# ==============================================================================
#  ArttulOS Automated LIVE ISO Builder v22.0 (Base64 Injection)
#
#  - DEFINITIVE FIX: My apologies. The --add-file argument is not
#    universally available. This version uses a 100% reliable method:
#    the branding images are base64-encoded and embedded directly into the
#    kickstart. The %post script then decodes them back into files.
#  - This method has ZERO external dependencies and will work on all versions
#    of livemedia-creator.
#
#  Written by: Natalie Spiva, ArttulOS Project
#  Rewritten and Corrected by: AI Assistant
# ==============================================================================

# --- Shell Colors ---
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'

# --- Helper Functions ---
error_exit() {
    echo -e "\n${RED}BUILD FAILED: $2${NC}" >&2
    echo -e "${YELLOW}Build directory and logs retained at: $1${NC}"
    exit 1
}

print_step() {
    CURRENT_STEP=$((CURRENT_STEP + 1))
    echo -e "\n${YELLOW}--> Step ${CURRENT_STEP}/${TOTAL_STEPS}: $1${NC}"
}

# --- Configuration ---
DISTRO_NAME="ArttulOS"
DISTRO_VERSION="9.6"
ASSET_REPO_URL="https://github.com/Sprunglesonthehub/arttulos-assets.git"
SOURCE_SIDEBAR_IMAGE="A.png"
SOURCE_TOPBAR_IMAGE="fox.png"
KS_FILENAME="arttulos-live.ks"

# --- Script Internals ---
BUILD_DIR_NAME="build_temp"
ASSET_DIR_NAME="arttulos-assets"
BUILD_MODE="Live"
TOTAL_STEPS=4

# ============================ KICKSTART GENERATION ============================

generate_kickstart() {
    local kickstart_file_path="$1"
    local sidebar_base64="$2"
    local topbar_base64="$3"

    print_step "Generating Kickstart file..."
    
    # This heredoc now includes placeholders for the base64 image data.
    cat > "${kickstart_file_path}" <<EOF
# Generated by ArttulOS Builder v22.0
#version=RHEL9
text
xconfig --startxonboot
keyboard 'us'
rootpw --iscrypted --lock locked
lang en_US.UTF-8
shutdown
timezone US/Eastern
network --bootproto=dhcp --device=link --activate
firewall --enabled --service=mdns
selinux --enforcing
services --disabled="sshd" --enabled="NetworkManager,ModemManager"

repo --name="BaseOS" --baseurl=https://dl.rockylinux.org/pub/rocky/9/BaseOS/\$basearch/os/
repo --name="AppStream" --baseurl=https://dl.rockylinux.org/pub/rocky/9/AppStream/\$basearch/os/
repo --name="CRB" --baseurl=https://dl.rockylinux.org/pub/rocky/9/CRB/\$basearch/os/
repo --name="extras" --baseurl=https://dl.rockylinux.org/pub/rocky/9/extras/\$basearch/os
repo --name="elrepo-kernel" --baseurl=https://elrepo.org/linux/kernel/el9/\$basearch/

bootloader --location=none
zerombr
clearpart --all --initlabel
part / --fstype="ext4" --size=8192

%packages
@anaconda-tools
@base-x
@core
@fonts
@gnome-desktop
@guest-desktop-agents
@hardware-support
@internet-browser
@multimedia
@networkmanager-submodules
@workstation-product
dracut-live
elrepo-release
kernel-ml
-kernel
aajohan-comfortaa-fonts
anaconda-install-env-deps
anaconda-live
chkconfig
glibc-all-langpacks
initscripts
libreoffice-calc
libreoffice-impress
libreoffice-writer
memtest86+
-@dial-up
-@input-methods
-@standard
-gfs2-utils
-reiserfs-utils
%end

%post --log=/root/ks-post.log --erroronfail
# LIVESYS setup
useradd -c "Live System User" liveuser
passwd -d liveuser > /dev/null
usermod -aG wheel liveuser > /dev/null
passwd -d root > /dev/null
echo "localhost" > /etc/hostname
rm -f /var/lib/rpm/__db*
rm -f /etc/machine-id && touch /etc/machine-id

# --- ArttulOS Branding and Setup ---
echo "Applying ArttulOS branding..."
sed -i "s/NAME=\"Rocky Linux\"/NAME=\"${DISTRO_NAME}\"/" /etc/os-release
sed -i "s/Rocky Linux release/${DISTRO_NAME} release/" /etc/redhat-release

# THE FIX: Decode the embedded base64 data back into image files.
echo "Decoding branding images..."
cat << 'IMAGE_EOF' | base64 --decode > /usr/share/anaconda/pixmaps/sidebar-logo.png
${sidebar_base64}
IMAGE_EOF

cat << 'IMAGE_EOF' | base64 --decode > /usr/share/anaconda/pixmaps/topbar-logo.png
${topbar_base64}
IMAGE_EOF

# GDM Auto-login
cat > /etc/gdm/custom.conf << EOT
[daemon]
AutomaticLoginEnable=True
AutomaticLogin=liveuser
EOT

# Installer icon on desktop
if [ -f /usr/share/applications/liveinst.desktop ]; then
  mv /usr/share/applications/liveinst.desktop /usr/share/applications/anaconda.desktop
  sed -i 's/NoDisplay=true/NoDisplay=false/' /usr/share/applications/anaconda.desktop
  sed -i 's/Rocky Linux/Install ${DISTRO_NAME}/' /usr/share/applications/anaconda.desktop
  mkdir -p ~liveuser/Desktop
  cp /usr/share/applications/anaconda.desktop ~liveuser/Desktop/
  chown liveuser:liveuser ~liveuser/Desktop/anaconda.desktop
fi

chown -R liveuser:liveuser /home/liveuser/
restorecon -R /home/liveuser/
echo "ArttulOS post-install script finished."
%end
EOF
    echo -e "${GREEN}    Kickstart file generated successfully.${NC}"
}

# ============================ MAIN BUILD LOGIC ============================

main() {
    if ! command -v livemedia-creator &> /dev/null; then
        echo -e "${RED}Error: 'livemedia-creator' command not found.${NC}" >&2; exit 1
    fi
    if [ "$EUID" -ne 0 ]; then
      echo -e "${RED}Error: This script must be run with sudo.${NC}" >&2; exit 1
    fi

    CURRENT_STEP=0
    local CWD; CWD="$(pwd)"
    local BUILD_DIR="${CWD}/${BUILD_DIR_NAME}"
    local FINAL_ISO_NAME="${DISTRO_NAME}-${DISTRO_VERSION}-${BUILD_MODE}.iso"
    local FINAL_ISO_PATH="${CWD}/${FINAL_ISO_NAME}"

    echo -e "${BLUE}======================================================================${NC}"
    echo -e "${BLUE}  ArttulOS Automated LIVE ISO Builder v22.0                             ${NC}"
    echo -e "${BLUE}======================================================================${NC}"

    echo -e "\n${BLUE}Starting build process...${NC}"
    rm -rf "$BUILD_DIR"; mkdir -p "$BUILD_DIR" || error_exit "$BUILD_DIR" "Could not create build directory."

    local ASSET_DIR="${BUILD_DIR}/${ASSET_DIR_NAME}"
    print_step "Cloning, Processing, and Encoding Assets..."
    git clone --quiet "$ASSET_REPO_URL" "$ASSET_DIR" || error_exit "$BUILD_DIR" "Failed to clone Git repo."
    
    local SIDEBAR_IMG_PATH="${BUILD_DIR}/arttulos-sidebar.png"
    local TOPBAR_IMG_PATH="${BUILD_DIR}/arttulos-topbar.png"
    convert "${ASSET_DIR}/${SOURCE_SIDEBAR_IMAGE}" -resize 180x230\! "$SIDEBAR_IMG_PATH" || error_exit "$BUILD_DIR" "ImageMagick failed on sidebar image."
    convert "${ASSET_DIR}/${SOURCE_TOPBAR_IMAGE}" -resize 150x25\! "$TOPBAR_IMG_PATH" || error_exit "$BUILD_DIR" "ImageMagick failed on topbar image."
    
    # THE FIX: Encode images to base64 to embed them in the kickstart file.
    local SIDEBAR_BASE64; SIDEBAR_BASE64=$(base64 -w 0 "$SIDEBAR_IMG_PATH")
    local TOPBAR_BASE64; TOPBAR_BASE64=$(base64 -w 0 "$TOPBAR_IMG_PATH")
    if [ -z "$SIDEBAR_BASE64" ] || [ -z "$TOPBAR_BASE64" ]; then
        error_exit "$BUILD_DIR" "Failed to base64-encode branding images."
    fi
    echo -e "${GREEN}    Assets are encoded and ready.${NC}"

    generate_kickstart "${BUILD_DIR}/${KS_FILENAME}" "$SIDEBAR_BASE64" "$TOPBAR_BASE64"

    print_step "Building the Live ISO with 'livemedia-creator'..."
    echo -e "${YELLOW}This will take a long time and download several GB of packages.${NC}"
    echo -e "${YELLOW}Logs will be available in: ${BUILD_DIR}/logs${NC}"
    
    livemedia-creator \
        --make-iso \
        --ks="${BUILD_DIR}/${KS_FILENAME}" \
        --project="${DISTRO_NAME}" \
        --releasever=9 \
        --resultdir="${BUILD_DIR}/result" \
        --logfile="${BUILD_DIR}/logs/livemedia.log" \
        || error_exit "$BUILD_DIR" "livemedia-creator failed. Check logs."

    print_step "Finalizing Build..."
    local RESULT_ISO_PATH; RESULT_ISO_PATH=$(find "${BUILD_DIR}/result" -name "*.iso" -print -quit)
    if [ -f "$RESULT_ISO_PATH" ]; then
        mv "$RESULT_ISO_PATH" "$FINAL_ISO_PATH"
    else
        error_exit "$BUILD_DIR" "Could not find the final ISO in the result directory."
    fi

    rm -rf "$BUILD_DIR"
    if [ -n "$SUDO_USER" ]; then
        chown "$SUDO_USER:$SUDO_USER" "$FINAL_ISO_PATH"
    fi

    echo -e "\n${GREEN}======================================================================${NC}"
    echo -e "${GREEN}  BUILD COMPLETE!                                                     ${NC}"
    echo -e "${GREEN}  Your '${BUILD_MODE}' ArttulOS ISO is ready:                         ${NC}"
    echo -e "${YELLOW}  ${FINAL_ISO_PATH}${NC}"
    echo -e "${GREEN}======================================================================${NC}"
}

main "$@"
